name: Error Message Test

on: 
    workflow_dispatch:
    release:
        types: [created]
jobs:
    build:
        permissions:
          id-token: write # For signing
          contents: read # For repo checkout.
          actions: read # For getting workflow run info.
        uses: enteraga6/slsa-github-generator/.github/workflows/builder_bazel_slsa3.yml@main
        with:
            targets: "//src:fib //src:hello //src/internal:fib2 //src/internal:test" #USER INPUTTED MATERIAL
    download:
            needs: [build]
            runs-on: ubuntu-latest
            steps:
            - name: Download Attestation
              uses: actions/download-artifact@v3
              with:
                name: "${{ needs.build.outputs.attestations-download-name }}"
