name: Generate Fib From SLSA Framework Bazel Builder

on: 
    workflow_dispatch:
    release:
        types: [created]
    push:
        tags:
            - v*.*.*
jobs:
    build:
        permissions:
          id-token: write # For signing
          contents: read # For repo checkout.
          actions: read # For getting workflow run info.
        uses: slsa-framework/slsa-github-generator/.github/workflows/builder_bazel_slsa3.yml@main
        with:
            targets: "//src:fib"
